Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("userName").Set "tuto" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("userName")_;_script infofile_;_ZIP::ssf1.xml_;_
Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("userName").Set "tutorial" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("userName")_;_script infofile_;_ZIP::ssf2.xml_;_
Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("password").SetSecure "5b7ca4a3e9bc4771b57e4fb01bab8c40870ba77eec50" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").WebEdit("password")_;_script infofile_;_ZIP::ssf3.xml_;_
Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").Image("Sign-In").Click 33,7 @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Welcome: Mercury Tours").Image("Sign-In")_;_script infofile_;_ZIP::ssf4.xml_;_
Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebRadioGroup("tripType").Select "oneway" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebRadioGroup("tripType")_;_script infofile_;_ZIP::ssf5.xml_;_
Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("passCount").Select "2" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("passCount")_;_script infofile_;_ZIP::ssf6.xml_;_
Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromPort").Select "Frankfurt" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromPort")_;_script infofile_;_ZIP::ssf7.xml_;_
Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromMonth").Select "September" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromMonth")_;_script infofile_;_ZIP::ssf8.xml_;_
Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromDay").Select "22" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("fromDay")_;_script infofile_;_ZIP::ssf9.xml_;_
Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("toPort").Select "New York" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("toPort")_;_script infofile_;_ZIP::ssf10.xml_;_
Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("toMonth").Select "September" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("toMonth")_;_script infofile_;_ZIP::ssf11.xml_;_
Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("toDay").Select "28" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("toDay")_;_script infofile_;_ZIP::ssf12.xml_;_
Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebRadioGroup("servClass").Select "Business" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebRadioGroup("servClass")_;_script infofile_;_ZIP::ssf13.xml_;_
Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("airline").Select "Unified Airlines" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").WebList("airline")_;_script infofile_;_ZIP::ssf14.xml_;_
Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").Image("findFlights").Click 49,7 @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Find a Flight: Mercury").Image("findFlights")_;_script infofile_;_ZIP::ssf15.xml_;_
Browser("Welcome: Mercury Tours").Page("Select a Flight: Mercury").WebRadioGroup("outFlight").Select "Pangea Airlines$362$274$9:17" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Select a Flight: Mercury").WebRadioGroup("outFlight")_;_script infofile_;_ZIP::ssf16.xml_;_
Browser("Welcome: Mercury Tours").Page("Select a Flight: Mercury").WebRadioGroup("inFlight").Select "Blue Skies Airlines$631$273$14:30" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Select a Flight: Mercury").WebRadioGroup("inFlight")_;_script infofile_;_ZIP::ssf17.xml_;_
Browser("Welcome: Mercury Tours").Page("Select a Flight: Mercury").Image("reserveFlights").Click 45,7 @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Select a Flight: Mercury").Image("reserveFlights")_;_script infofile_;_ZIP::ssf18.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passFirst0").Set "Abc" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passFirst0")_;_script infofile_;_ZIP::ssf19.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passLast0").Set "Def" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passLast0")_;_script infofile_;_ZIP::ssf20.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebList("pass.0.meal").Select "Bland" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebList("pass.0.meal")_;_script infofile_;_ZIP::ssf21.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passFirst1").Set "ghj" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passFirst1")_;_script infofile_;_ZIP::ssf22.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passLast1").Set "oiu" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("passLast1")_;_script infofile_;_ZIP::ssf23.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebList("pass.1.meal").Select "Kosher" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebList("pass.1.meal")_;_script infofile_;_ZIP::ssf24.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("creditnumber").Set "123456789" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("creditnumber")_;_script infofile_;_ZIP::ssf25.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebList("cc_exp_dt_mn").Select "07" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebList("cc exp dt mn")_;_script infofile_;_ZIP::ssf26.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebList("cc_exp_dt_yr").Select "2004" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebList("cc exp dt yr")_;_script infofile_;_ZIP::ssf27.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("cc_frst_name").Set "abc" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("cc frst name")_;_script infofile_;_ZIP::ssf28.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("cc_mid_name").Set "def" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("cc mid name")_;_script infofile_;_ZIP::ssf29.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("cc_last_name").Set "def" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("cc last name")_;_script infofile_;_ZIP::ssf30.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebElement("HomeFlightsHotelsCar RentalsCr").Click @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebElement("HomeFlightsHotelsCar RentalsCr")_;_script infofile_;_ZIP::ssf31.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebCheckBox("ticketLess").Set "ON" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebCheckBox("ticketLess")_;_script infofile_;_ZIP::ssf32.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("billAddress1").Set "Address" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("billAddress1")_;_script infofile_;_ZIP::ssf33.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("billAddress2").Set "Address" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("billAddress2")_;_script infofile_;_ZIP::ssf34.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("billCity").Set "Bostan" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("billCity")_;_script infofile_;_ZIP::ssf35.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("billZip").Set "500500" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebEdit("billZip")_;_script infofile_;_ZIP::ssf36.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebList("billCountry").Select "VIRGIN ISLANDS" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebList("billCountry")_;_script infofile_;_ZIP::ssf37.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebElement("HomeFlightsHotelsCar RentalsCr").Click @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebElement("HomeFlightsHotelsCar RentalsCr")_;_script infofile_;_ZIP::ssf38.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebCheckBox("ticketLess_2").Set "ON" @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").WebCheckBox("ticketLess 2")_;_script infofile_;_ZIP::ssf39.xml_;_
Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").Image("buyFlights").Click 73,3 @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Book a Flight: Mercury").Image("buyFlights")_;_script infofile_;_ZIP::ssf40.xml_;_
Browser("Welcome: Mercury Tours").Page("Flight Confirmation: Mercury").Image("Logout").Click @@ hightlight id_;_Browser("Welcome: Mercury Tours").Page("Flight Confirmation: Mercury").Image("Logout")_;_script infofile_;_ZIP::ssf41.xml_;_
